name: Easy CP PoC
on:
  pull_request_target:
    types: [labeled]

jobs:
  cherry-pick:
    if: "${{ github.event.label.name == 'cp: beta' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Create PR on CP success
        env:
          FLUTTERACTIONSBOT_CP_TOKEN: ${{ secrets.FLUTTERACTIONSBOT_CP_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          CHANNEL: "beta"
        run: |
          echo "Attempting to create PR with title: [CP-${CHANNEL}]${PR_TITLE}"
